# Site settings
title: Daniel Pellatt
url: "https://danielpellatt.github.io" # the base hostname & protocol for your site
description: |+
  I recently obtained my Ph.D. Economics from the University of California San Diego. My field of research is econometrics.<br><br><br>You can reach me at <b>dpellatt@ucsd.edu</b>

theme: jekyll-theme-minimal


github:
  is_user_page: false

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
powered_by: false
